services:

  php:
    build:
      target: ci
      dockerfile: Dockerfile.php
    networks:
      - web-ci
    volumes:
      - .:/var/www/html/

  node:
    build:
      args:
        USER_ID: ${SPIN_USER_ID}
        GROUP_ID: ${SPIN_GROUP_ID}
      dockerfile: Dockerfile.node
    volumes:
      - .:/usr/src/app/
    networks: 
      - web-ci

  mailpit:
    image: axllent/mailpit
    networks:
      - web-ci

networks:
  web-ci: