services:

  queue:
    build:
      target: development
      args:
        USER_ID: ${SPIN_USER_ID}
        GROUP_ID: ${SPIN_GROUP_ID}
      dockerfile: Dockerfile.php
    environment:
      PHP_FPM_POOL_NAME: "laravel_queue"
    entrypoint: ''
    command: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
    networks:
      - development
    labels:
      - "traefik.enable=false"
