services:

  meilisearch:
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - development
    depends_on:
      spin-database:
        condition: service_healthy
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.meilisearch.rule=Host(`meilisearch.dev.test`)"
        - "traefik.http.routers.meilisearch.entrypoints=websecure"
        - "traefik.http.routers.meilisearch.tls=true"
        - "traefik.http.services.meilisearch.loadbalancer.server.port=7700"
        - "traefik.http.services.meilisearch.loadbalancer.server.scheme=http"

volumes:
  meilisearch_data:
