services:

  meilisearch:
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - web-public
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first

volumes:
  meilisearch_data:
