services:

  redis:
    command: "valkey-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redispassword}"
    volumes:
      - redis_data:/data
    networks:
      - development

volumes:
  redis_data:
