services:

  horizon:
    entrypoint: ''
    command: ["php", "/var/www/html/artisan", "horizon"]
    healthcheck:
      test: ["CMD", "php", "/var/www/html/artisan", "horizon:status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    depends_on:
      - redis
      - php
