services:

  horizon:
    image: ${SPIN_IMAGE_DOCKERFILE_PHP}
    environment:
      APP_ENV: "${SPIN_DEPLOYMENT_ENVIRONMENT}"
    stop_grace_period: 30s
    networks:
      - web-public
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"
    deploy:
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 5s
        order: stop-first
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s