services:

  php:
    depends_on:
      mysql:
        condition: service_started

  mysql:
    networks:
      - development
    volumes:
      - ./.infrastructure/volume_data/mysql/database_data/:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: "rootpassword"
        MYSQL_DATABASE: "laravel"
        MYSQL_USER: "mysqluser"
        MYSQL_PASSWORD: "mysqlpassword"
    ports:
      - target: 3306
        published: 3306
        mode: host
