services:

  php:
    depends_on:
      mysql:
        condition: service_started

  mysql:
    networks:
      - development
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
        MYSQL_DATABASE: ${DB_DATABASE:-laravel}
        MYSQL_USER: ${DB_USERNAME:-laravel}
        MYSQL_PASSWORD: ${DB_PASSWORD:-laravel}
    ports:
      - target: 3306
        published: 3306
        mode: host

volumes:
  mysql_data:
