services:
  reverb:
    build:
      target: development
      args:
        USER_ID: ${SPIN_USER_ID}
        GROUP_ID: ${SPIN_GROUP_ID}
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/html/
    networks:
      - development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel-reverb.rule=Host(`reverb.dev.test`)"
      - "traefik.http.routers.laravel-reverb.entrypoints=websecure"
      - "traefik.http.routers.laravel-reverb.tls=true"
      - "traefik.http.services.laravel-reverb.loadbalancer.server.port=8000"
      - "traefik.http.services.laravel-reverb.loadbalancer.server.scheme=http"
    depends_on:
      php:
        condition: service_started
      spin-database:
        condition: service_healthy
