services:

  reverb:
    command: ["php", "/var/www/html/artisan", "--port=8000", "reverb:start"]
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "healthcheck-reverb"]
      start_period: 10s
