services:

  schedule:
    build:
      target: development
      args:
        USER_ID: ${SPIN_USER_ID}
        GROUP_ID: ${SPIN_GROUP_ID}
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/html/
    networks:
      - development
