services:

  php:
    depends_on:
      mariadb:
        condition: service_started

  mariadb:
    networks:
      - development
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
        MARIADB_ROOT_PASSWORD: "rootpassword"
        MARIADB_DATABASE: "laravel"
        MARIADB_USER: "mysqluser"
        MARIADB_PASSWORD: "mysqlpassword"
    ports:
      - target: 3306
        published: 3306
        mode: host

volumes:
  mariadb_data:
