services:

  php:
    depends_on:
      mariadb:
        condition: service_started

  mariadb:
    networks:
      - development
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
        MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
        MARIADB_DATABASE: ${DB_DATABASE:-laravel}
        MARIADB_USER: ${DB_USERNAME:-laravel}
        MARIADB_PASSWORD: ${DB_PASSWORD:-laravel}
    ports:
      - target: 3306
        published: 3306
        mode: host

volumes:
  mariadb_data:
