services:

  mariadb:
    networks:
      - web-public
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "1"
      MARIADB_DATABASE: "${DB_DATABASE}"
      MARIADB_USER: "${DB_USERNAME}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
    deploy:
      placement:
        constraints:
          - node.role==manager
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_custom_conf:/etc/mysql/conf.d
      - mariadb_shared:/shared

  ssh:
    # We use an SSH image so we can securely tunnel into the Docker network with 
    # tools like Sequel Pro, TablePlus, Sequel Ace, etc.
    # Learn more how to secure your tunnel here: https://github.com/serversideup/docker-ssh
    image: serversideup/docker-ssh:v2.0.0
    ports:
      - target: 2222
        published: 2222
        mode: host
    environment:
      # Change the keys below to your own keys 
      AUTHORIZED_KEYS: >
        "# Start Keys
         ssh-ed25519 1234567890abcdefghijklmnoqrstuvwxyz user-a
         ssh-ed25519 abcdefghijklmnoqrstuvwxyz1234567890 user-b
         # End Keys"
      # Be sure to configure the allowed IP addresses too
      ALLOWED_IPS: "AllowUsers *@127.0.0.1"
    volumes:
      - tunnel_ssh_host_keys:/etc/ssh/ssh_host_keys
    networks:
        - web-public

volumes:
  mariadb_data:
  mariadb_custom_conf:
  mariadb_shared:
  tunnel_ssh_host_keys: