services:

  php:
    depends_on:
      postgres:
        condition: service_started

  postgres:
    networks:
      - development
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
        POSTGRES_DB: ${DB_DATABASE:-laravel}
        POSTGRES_USER: ${DB_USERNAME:-laravel}
        POSTGRES_PASSWORD: ${DB_PASSWORD:-laravel}
    ports:
      - target: 5432
        published: 5432
        mode: host

volumes:
  postgres_data:
