services:

  php:
    depends_on:
      postgres:
        condition: service_started

  postgres:
    networks:
      - development
    volumes:
      - ./.infrastructure/volume_data/postgres/database_data/:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: "laravel"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgrespassword"
    ports:
      - target: 5432
        published: 5432
        mode: host
